### ISSUE TITLE
Unify naming convention

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/go-ws-transport#14]
Currently modules are named `<lang>-libp2p-<tool>`, this repo does not adhere to it. I propose renaming it to `go-libp2p-websocket`, like the `js-libp2p-websocket` repo.

**Comment by lgierth** [comment]
All of the go transports are named like this: go-ws-, go-tcp-, go-utp, etc. -- renames unfortunately need a lot of care in go because of import paths. Not saying we shouldn't do it, just that it's a bit of effort.

**Comment by whyrusleeping** [comment]
These packages arent necessarily tied to libp2p, They are a layer below really.

**Comment by whyrusleeping** [comment]
I would propose renaming js-libp2p-websocket to js-ws-transport
