### ISSUE TITLE
Prevent Accept from hanging when the Listener is closed.

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-ws-transport#26]
Currently, we don't check if the Listener is closed in `Accept`. It can hang indefinitely. This shouldn't be causing any real-world bugs but it's still not good.

**Comment by marten-seemann** [comment]
I think we do now: https://github.com/libp2p/go-ws-transport/blob/3bad9fbbd930ae385cc89802f8cdbd1ea32e024f/listener.go#L109-L110
