### ISSUE TITLE
Handle omission of default ports :80 and :443

### ISSUE THREAD

**Issue by ghost** [libp2p/go-ws-transport#8]
HTTP clients regularly omit the port in the Host header if its default :80 or :443. In practice this means that `ws.Conn.LocalAddr()` and `ws.Conn.RemoteAddr()` sometimes only contain a domain name or IP address, but not a port. `manet.WrapNetConn()` can't deal with that, errors, and the /ws listener shuts down.

The listener should ensure it only hands addresses to `manet.WrapNetConn()` that contain a port.

```
Swarm listening on /ip4/127.0.0.1/tcp/8081/ws
00:45:52.113 DEBUG       conn: listener closing: <peer.ID Vcj9MA> /ip4/127.0.0.1/tcp/8081/ws listen.go:65
00:45:52.114 DEBUG       conn: listener closed: <peer.ID Vcj9MA> /ip4/127.0.0.1/tcp/8081/ws listen.go:61
00:45:52.114 WARNI     swarm2: swarm listener accept error: peerstream listener failed: failed to convert nconn.LocalAddr: missing port in address 178.62.215.134 swarm_listen.go:135
```

The listener itself is on :8081, but it's behind a reverse proxy on :80, and thus the incoming Host headers don't contain a port. For now I've worked around this by having the reverse proxy explicitly add the port.

**Comment by lgierth** [comment]
This is the workaround applied in nginx for now: https://github.com/ipfs/infrastructure/commit/f7549cfbff033f84c0ad4b81f692e8b8e26e9c1a#diff-2f68a91ca8b05c2bb103139015d84c6aR113

It makes sure there's always a port on the end of the Host header.

**Comment by marten-seemann** [comment]
Not sure if this an issue any more. We don't read the host header, as far as I can tell.
